import { Router } from "express";
import authRoutes from "./authRoutes.js";
import subscriptionRoutes from "./subscriptionRoutes.js";
import scanRoutes from "./scanRoutes.js";
import billingRoutes from "./billingRoutes.js";
import gmailRoutes from "./gmailRoutes.js";
import suggestionRoutes from "./suggestionRoutes.js";
import plaidRoutes from "./plaidRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import userRoutes from "./userRoutes.js";
import newsletterRoutes from "./newsletterRoutes.js";

const router = Router();
router.use("/auth", authRoutes);
router.use("/subscriptions", subscriptionRoutes);
router.use("/scan", scanRoutes);
router.use("/billing", billingRoutes);
router.use("/gmail", gmailRoutes);
router.use("/suggestions", suggestionRoutes);
router.use("/plaid", plaidRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/users", userRoutes);
router.use("/newsletter", newsletterRoutes);
export default router;
